[test6.1]
test_cases_file = ./tests/end-to-end/test_cases.json
results_file = ./tests/end-to-end/results/test6.1.json
config_file = ./tests/cfg/shai_def_config_1.conf
repeats = 10
section_size = 0
extended_search = false


[test6.2]
test_cases_file = ./tests/end-to-end/test_cases.json
results_file = ./tests/end-to-end/results/test6.2.json
config_file = ./tests/cfg/shai_def_config_1.conf
repeats = 10
section_size = 0
extended_search = true


[test6.3]
test_cases_file = ./tests/end-to-end/test_cases.json
results_file = ./tests/end-to-end/results/test6.3.json
config_file = ./tests/cfg/shai_def_config_1.conf
repeats = 10
section_size = 20
extended_search = false
