# This is a config to check whether each registered test works

[test1.0]
collection_dir = ./tests/sample-10
test_cases_file = ./tests/sample-10/test_cases.short.json
batch_size = 32
top_k = 5
index_dir_name = .index
results_file = ./tests/regress/results/test1.0.json
config_file = ./tests/cfg/shai_def_config_0.conf

[test2.0]
collection_dir = ./tests/sample-10
test_cases_file = ./tests/sample-10/test_cases.short.json
batch_size = 32
top_k = 5
top_k_extended = 10
index_dir_name = .index
results_file = ./tests/regress/results/test2.0.json
config_file = ./tests/cfg/shai_def_config_0.conf

[test3.0]
collection_dir = ./tests/sample-10
test_cases_file = ./tests/sample-10/test_cases.short.json
batch_size = 32
top_k = 5
passage_size = 20
index_dir_name = .index
results_file = ./tests/regress/results/test3.0.json
config_file = ./tests/cfg/shai_def_config_0.conf

[test4.0]
test_cases_file = ./tests/classifier-100/test_cases.short.json
results_file = ./tests/regress/results/test4.0.json
config_file = ./tests/cfg/shai_def_config_0.conf

[test6.0]
test_cases_file = ./tests/end-to-end/test_cases.short.json
results_file = ./tests/regress/results/test6.0.json
config_file = ./tests/cfg/shai_def_config_0.conf
repeats = 1
section_size = 0
extended_search = false

[test_integration.0]
test_cases_file = ./tests/regress/test_cases.short.json
results_file = ./tests/test-results.bak/test_integration.0.json
