# Warmup
[test5.heavy.100.extended]
test_cases_file = ./tests/end-to-end/test_cases.json
results_file = ./tests/end-to-end/results/test0.json
config_file = ./tests/cfg/shai_def_config_heavy.conf
db_path = ./tests/sample-100/docs/
repeats = 1
section_rows = 0
extended_search = true

# Light config, sample-1000, no extended, no sections
[test5.light.1000.basic]
test_cases_file = ./tests/end-to-end/test_cases.json
results_file = ./tests/end-to-end/results/test5.light.1000.basic.json
config_file = ./tests/cfg/shai_def_config_light.conf
db_path = ./tests/sample-1000/docs/
repeats = 1
section_rows = 0
extended_search = false

# Light config, sample-1000, extended search, no sections
[test5.light.1000.extended]
test_cases_file = ./tests/end-to-end/test_cases.json
results_file = ./tests/end-to-end/results/test5.light.1000.extended.json
config_file = ./tests/cfg/shai_def_config_light.conf
db_path = ./tests/sample-1000/docs/
repeats = 1
section_rows = 0
extended_search = true

# Light config, sample-1000, no extended, with sections
[test5.light.1000.sections]
test_cases_file = ./tests/end-to-end/test_cases.json
results_file = ./tests/end-to-end/results/test5.light.1000.sections.json
config_file = ./tests/cfg/shai_def_config_light.conf
db_path = ./tests/sample-1000/docs/
repeats = 1
section_rows = 20
extended_search = false

# Heavy config, sample-1000, no extended, no sections
[test5.heavy.1000.basic]
test_cases_file = ./tests/end-to-end/test_cases.json
results_file = ./tests/end-to-end/results/test5.heavy.1000.basic.json
config_file = ./tests/cfg/shai_def_config_heavy.conf
db_path = ./tests/sample-1000/docs/
repeats = 1
section_rows = 0
extended_search = false

# Heavy config, sample-1000, extended search, no sections
[test5.heavy.1000.extended]
test_cases_file = ./tests/end-to-end/test_cases.json
results_file = ./tests/end-to-end/results/test5.heavy.1000.extended.json
config_file = ./tests/cfg/shai_def_config_heavy.conf
db_path = ./tests/sample-1000/docs/
repeats = 1
section_rows = 0
extended_search = true

# Heavy config, sample-1000, no extended, with sections
[test5.heavy.1000.sections]
test_cases_file = ./tests/end-to-end/test_cases.json
results_file = ./tests/end-to-end/results/test5.heavy.1000.sections.json
config_file = ./tests/cfg/shai_def_config_heavy.conf
db_path = ./tests/sample-1000/docs/
repeats = 1
section_rows = 20
extended_search = false
