[test1]
test_file = ./tests/test1.py

[test2]
test_file = ./tests/test2.py

[test3]
test_file = ./tests/test3.py

[test4]
test_file = ./tests/test4.py

[test5]
test_file = ./tests/test5.py

[test_integration]
test_file = ./tests/test_integration.py
